### ISSUE TITLE
7.2 启动报错

### ISSUE THREAD

**Issue by FFFro** [tenlee2012/elasticsearch-analysis-hao#2]
java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/exc/InputCoercionException
        at com.fasterxml.jackson.databind.deser.BasicDeserializerFactory.createMapDeserializer(BasicDeserializerFactory.java:1376) ~[?:?]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:387) ~[?:?]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349) ~[?:?]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264) ~[?:?]
        at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244) ~[?:?]
        at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142) ~[?:?]
        at com.fasterxml.jackson.databind.DeserializationContext.findRootValueDeserializer(DeserializationContext.java:479) ~[?:?]
        at com.fasterxml.jackson.databind.ObjectMapper._findRootDeserializer(ObjectMapper.java:4405) ~[?:?]
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4214) ~[?:?]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3099) ~[?:?]
        at com.itenlee.search.analysis.help.JSONUtil.lambda$parseJSON$2(JSONUtil.java:32) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_231]
        at com.itenlee.search.analysis.help.JSONUtil.parseJSON(JSONUtil.java:32) ~[?:?]
        at com.itenlee.search.analysis.core.Dictionary.loadDict(Dictionary.java:96) ~[?:?]
        at com.itenlee.search.analysis.core.Dictionary.initial(Dictionary.java:65) ~[?:?]
        at com.itenlee.search.analysis.lucence.Configuration.<init>(Configuration.java:125) ~[?:?]
        at org.elasticsearch.index.analysis.hao.HaoTokenizerFactory.<init>(HaoTokenizerFactory.java:34) ~[?:?]
        at org.elasticsearch.index.analysis.hao.HaoTokenizerFactory.getHttpSmartTokenizerFactory(HaoTokenizerFactory.java:38) ~[?:?]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildMapping(AnalysisRegistry.java:343) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.index.analysis.AnalysisRegistry.buildTokenizerFactories(AnalysisRegistry.java:179) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:164) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.index.IndexService.<init>(IndexService.java:175) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:399) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:564) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:513) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:166) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.createIndices(IndicesClusterStateService.java:507) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:269) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.lambda$callClusterStateAppliers$5(ClusterApplierService.java:495) ~[elasticsearch-7.2.0.jar:7.2.0]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_231]
        at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:493) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:464) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:165) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:688) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.2.0.jar:7.2.0]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.2.0.jar:7.2.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_231]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.core.exc.InputCoercionException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_231]
        at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:817) ~[?:1.8.0_231]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_231]
        ... 40 more

**Comment by tenlee2012** [comment]
非常抱歉由于我的疏忽给您使用造成了困扰。
由于`elasticsearch`每个版本自依赖的`jackson`版本不同导致的。
es 7.2.0依赖的`jackson`版本是`2.8.11`，本插件依赖的是`2.10.4导致了依赖冲突。
所以在打包的时候不仅要修改`elasticsearch.version`属性，还要修改`jackson.version`属性，使其版本对应。
我已经打包好上传了，请到release页面下载。
